site_name: 🌱 DESMA28 Interactivity
theme: 
  name: simple-blog
  sidebar: true
  navigation_depth: 2
  components:
    title: false
    preview: true
  theme_style: light
extra_css:
  - extra.css
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.9.0/highlight.min.js
nav:
  - 🏠 Home: index.md
  - 📜 Syllabus: syllabus.md
  - 📅 Schedule: schedule.md
  - 📌 Assignments: https://docs.google.com/document/d/1h-4Y8c9U50v0dFKp67S9M0lpJyYsVp5zOFEex2xJTKM/edit?usp=sharing
  - 🛠️ Workshop Notes: https://docs.google.com/document/d/1zyBdAmaZ4UuZhEBmgCxaAuBFuCJw5aHM6tXkqNaO1Ow/edit?usp=sharing
plugins:
  - exclude:
      glob: 